# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='isfavourite',
            new_name='favourite',
        ),
    ]
